### ISSUE TITLE
Android Studio 3.5 cannot find symbols in valid code

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4436]
### Actual behaviour
Android Studio 3.5 cannot find Mockito symbols in tests.
All references are red.
Code completion does not work.
When run, code compiles and works correctly.

### Expected behaviour
IDE can resolve all symbols in valid code.
 
### Steps to reproduce
Open any test that contains references to `Mock` annotation or `thenReturn` - it's red.
I boosted max heap size to exclude issues with indexer.

**I just want to confirm** that this is also experienced by others. It looks for me like Android Studio bug, but it could as well be just my wonky setup or some legacy `.idea` settings issue.

**Comment by AndyScherzinger** [comment]
@ezaquarii just checked `TestPreferenceManager` ans all dependencies (including `Mock`) are being resolved and it works fine in my 3.5 AS.

@tobiasKaminsky do you experience any issues?

**Comment by ezaquarii** [comment]
@AndyScherzinger, what AS version do you run? What java version?

**Comment by AndyScherzinger** [comment]
Don't know the version code, but it's 3.5 / latest stable on Windows 10 and Java 8

**Comment by ezaquarii** [comment]
Zapping AS config fixed the problem. `¯\_( ͡° ͜ʖ ͡°)_/¯`

**Comment by steffanc** [comment]
@ezaquarii also seeing this issue. I'm onAndroid Studio 3.5.1
Build #AI-191.8026.42.35.5900203, built on September 25, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

Can you explain exactly what you mean by "zapping" the AS config?

I tried clean building, invalidate caches and restart, re-cloning the code base and can’t seem to fix it

**Comment by ezaquarii** [comment]
I deleted the AS configuration directories from my $HOME, .idea and started with clean install.

**Comment by ab-chesspad** [comment]
Confirming on AS 3.5.3 on Ubuntu 16.04.
Deleting AS config is not an option because of lots of my own preferences.
Using 
    testImplementation 'org.mockito:mockito-core:2.4.0'
    testImplementation 'org.powermock:powermock-core:1.7.0RC2'
    testImplementation 'org.powermock:powermock-module-junit4:1.7.0RC2'
    testImplementation 'org.powermock:powermock-api-mockito2:1.7.0RC2'
because newer versions do not support powermock.
